PROJETO01/PROJETO01/Controllers/BarController.cs
using Microsoft.AspNetCore.Mvc;
using PROJETO01.Dados.EntityFramework;
using PROJETO01.Modelos;
using System.Linq;

namespace PROJETO01.Controllers
{
    public class BarController : Controller
    {
        public IActionResult Index(int Bar, string bar)
        {
           

            return View();
        }

        [HttpGet]
        public IActionResult Adicionar()
        {
            return View();
        }

        public IActionResult AdicionarConfirmacao(Bar bar)
        {
            var db = new Contexto();

            var obj = db.Bar.FirstOrDefault(B => B.BarID == bar.BarID);

            if (obj == null)
            {
                db.Bar.Add(bar);
            }
            else
            {
                obj.cnpj = bar.cnpj;
                obj.nome = bar.nome;
                obj.localizacao = bar.localizacao;
                obj.numero = bar.numero;

                db.Bar.Update(obj);
            }

            db.SaveChanges();

            return RedirectToAction("Listar");
        }

        [HttpGet]
        public IActionResult Editar(int barID)
        {
            var db = new Contexto();
            var bar = db.Bar.First(item => item.BarID == barID);
            return View("Adicionar", bar);
        }

        public IActionResult Listar()
        {

            //SELECT * FROM Estado
            var listaDeBares = new Contexto().Bar.ToList();

            return View(listaDeBares);
        }

        public IActionResult Excluir(int barID)
        {
            var db = new Contexto();
            var Bar = db.Bar.First(B => B.BarID == barID);
            db.Bar.Remove(Bar);
            db.SaveChanges();

            return RedirectToAction("Listar");
        }
    }
}

PROJETO01/PROJETO01/Controllers/CidadeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PROJETO01.Dados.EntityFramework;
using PROJETO01.Modelos;

namespace PROJETO01.Controllers
{
    public class CidadeController : Controller
    {
        public IActionResult Index(int Cidade, string cidade)
        {
            var objeto = new Cidade();
            objeto.CidadeId = Cidade;
            objeto.Nome = cidade;


            return View(objeto);
        }

        [HttpGet]
        public IActionResult Adicionar()
        {
            var db = new Contexto();
            ViewBag.Estado = db.Estado.ToList();
            return View();
        }

        public IActionResult AdicionarConfirmacao(Cidade cidade)
        {
            var db = new Contexto();

            var obj = db.Cidade.FirstOrDefault(C => C.Nome == cidade.Nome);

            if (obj == null)
            {
                db.Cidade.Add(cidade);
            }
            else
            {
                obj.Nome = cidade.Nome;
                db.Cidade.Update(obj);
            }

            db.SaveChanges();

            return RedirectToAction("Listar");
        }

        [HttpGet]
        public IActionResult Editar(int CidadeID)
        {
            var db = new Contexto();
            ViewBag.Estado = db.Estado.ToList();
            var cidade = db.Cidade.First(item => item.CidadeId == CidadeID);
            return View("Adicionar", cidade);
        }

        public IActionResult Listar()
        {

            //SELECT * FROM Estado
            var listaDeCidades = new Contexto().Cidade.ToList();

            return View(listaDeCidades);
        }

        public IActionResult Excluir(int CidadeID)
        {
            var db = new Contexto();
            var cidade = db.Cidade.First(c => c.CidadeId == CidadeID);
            db.Cidade.Remove(cidade);
            db.SaveChanges();

            return RedirectToAction("Listar");
        }
    }
}

PROJETO01/PROJETO01/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using PROJETO01.Dados.EntityFramework;
using PROJETO01.Modelos;
using System.Linq;

namespace PROJETO01.Controllers
{
    public class ClienteController : Controller
    {
       

        [HttpGet]
        public IActionResult Adicionar()
        {
            return View();
        }

        public IActionResult AdicionarConfirmacao(Cliente cliente)
        {
            var db = new Contexto();

            var obj = db.Cliente.FirstOrDefault(C => C.Nome == cliente.Nome);

            if (obj == null)
            {
                db.Cliente.Add(cliente);
            }
            else
            {
                obj.Nome = cliente.Nome;
                obj.Cpf = cliente.Cpf;
                obj.Email = cliente.Email;
                obj.Telefone= cliente.Telefone;
                obj.ClienteID= cliente.ClienteID;
                db.Cliente.Update(obj);
            }

            db.SaveChanges();

            return RedirectToAction("Listar");
        }

        [HttpGet]
        public IActionResult Editar(string ClienteID)
        {
            var db = new Contexto();
            var cliente = db.Cliente.First(item => item.ClienteID == ClienteID);
            return View("Adicionar", cliente);
        }

        public IActionResult Listar()
        {

            //SELECT * FROM Estado
            var listaDeClientes = new Contexto().Cliente.ToList();

            return View(listaDeClientes);
        }

        public IActionResult Excluir(string ClienteID)
        {
            var db = new Contexto();
            var cliente = db.Cliente.First(c => c.ClienteID == ClienteID);
            db.Cliente.Remove(cliente);
            db.SaveChanges();

            return RedirectToAction("Listar");
        }
    }
}

PROJETO01/PROJETO01/Controllers/EstadoController.cs
using Microsoft.AspNetCore.Mvc;
using PROJETO01.Dados.EntityFramework;
using PROJETO01.Modelos;
using PROJETO01.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PROJETO01.Controllers
{
    public class EstadoController : Controller
    {
        public IActionResult Index(string uf, string estado)
        {
            var objeto = new Estado();
            objeto.UF = uf;
            objeto.Nome = estado;

            return View(objeto);
        }

        [HttpGet]
        public IActionResult Adicionar()
        {
           
            return View();
        }

        public IActionResult AdicionarConfirmacao(Estado estado)
        {
            var db = new Contexto();

            var obj = db.Estado.FirstOrDefault(f => f.UF == estado.UF);

            if (obj == null)
            {
                db.Estado.Add(estado);
            }
            else
            {
                obj.Nome = estado.Nome;
                db.Estado.Update(obj);
            }
            
            db.SaveChanges();

            return RedirectToAction("Listar");
        }

        [HttpGet]
        public IActionResult Editar(string uf)
        {
            var db = new Contexto();
            var estado = db.Estado.First(item => item.UF == uf);
            return View("Adicionar", estado);
        }

        public IActionResult Listar() {

            //SELECT * FROM Estado
            var listaDeEstados = new Contexto().Estado.ToList();

            return View(listaDeEstados);
        }

        public IActionResult Excluir(string uf)
        {
            var db = new Contexto();
            var estado = db.Estado.First(f => f.UF == uf);
            db.Estado.Remove(estado);
            db.SaveChanges();

            return RedirectToAction("Listar");
        }
    }
}

PROJETO01/PROJETO01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]UBERVENTS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href'Times New Roman'al, Helvetica, sans-serifamondactacttka Small'ite.css" />
</head>
<body style="background-image :url(https://image.freepik.com/free-vector/abstract-city-map-with-pins-navigation-app_95169-1513.jpg) " >
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img src="/img/LOGO.PNG" alt="" width="40" height="40" class="d-inline-block align-text-top" />
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="margin-left:10px ; font-family:'Times New Roman', Times, serif'"> UBERVENTS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estado" asp-action="Listar">Estados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cidade" asp-action="Listar">Cidades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Listar">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bar" asp-action="Listar">Bares</a>
                        </li>
                    </ul>
                </div>
                <form class="form-inline my-2 my-lg-0">
                    <button class="btn btn-outline-primary my-2 my-sm-0 ml-2" type="submit">Entrar</button>
                    <button class="btn btn-outline-dark my-2 my-sm-0 ml-2" type="submit">Cadastros</button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>