PROJETO01/PROJETO01/Controllers/EventoController.cs
using Microsoft.AspNetCore.Mvc;

namespace PROJETO01.Controllers
{
    public class eventoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PROJETO01/PROJETO01/Views/Evento/Adicionar.cshtml
@model PROJETO01.Modelos.evento

    <form asp-controller="evento" asp-action="AdicionarConfirmacao" method="post">
        <div class="mb-3">
            <label for="nome" class="form-label">Nome:</label>
            <input asp-for="nome" type="text" class="form-control" placeholder="Digite seu nome do evento" />
        </div>
        <div class="mb-3">
            <label for="Taxa" class="form-label">Taxa:</label>
            <input asp-for="taxa" type="text" class="form-control" placeholder="Digite a taxa" />
        </div>
          <div class="mb-3">
            <label for="horario" class="form-label">Horario:</label>
            <input asp-for="horario" type="text" class="form-control" placeholder="Digite o horario" />
        </div>
         <div class="mb-3">
            <label for="EventoID" class="form-label">EventoID:</label>
            <input asp-for="EventoID" type="text" class="form-control" placeholder="Digite o ID do Evento" />
        </div>
         

        <a href="#" class="btn btn-secondary" onclick="javascript:history.back()">
            VOLTAR
        </a>

        <button type="submit" class="btn btn-success float-right">
            SALVAR
        </button>

    </form>
      

PROJETO01/PROJETO01/Views/Evento/Listar.cshtml
@model List<PROJETO01.Modelos.evento>
<div class="container-fluid " style= "border:groove; color:thick;background-color:white">
    <br />
<h3>
    CADASTRO DE EVENTOS
    <a class="btn btn-sm btn-dark float-right" href="/evento/Adicionar">
        + ADICIONAR
    </a>
</h3>

<table class="table table-hover ">
    <thead>
        <tr>
            <th>EventoID</th>
            <th>nome</th>
            <th>taxa</th>
            <th>horario</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.EventoID</td>
                <td>@item.nome</td>
                <td>@item.taxa</td>
                  <td>@item.horario</td>
                <td>
                    <a href="/evento/Editar?uf=@item.EventoID" class="btn btn-sm btn-warning">
                        Editar
                    </a>
                    <a href="/evento/Excluir?uf=@item.EventoID" class="btn btn-sm btn-danger">
                        Excluir
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

  </div>
     